### ISSUE TITLE
vaadin-avatar: img property

### ISSUE THREAD

**Issue by pekam** [vaadin/vaadin-avatar#2]
String property for the URL pointing at the image to display inside the avatar.

Should pass to an internal `img` element to get also support to `data:` etc.

Eventually, the component should have similar 3 properties for defining the content, as in the vcf component:
https://github.com/vaadin/incubator-avatar/blob/fd73de6bdbbb6f203191748fd55241001df4c97c/src/incubator-avatar.html#L106-L120

If `img` is defined, it's used.
Else if `abbr` is defined, it's used.
Else abbreviation is deduced from `name`.

**Comment by jouni** [comment]
To add to the list: if no img, abrr, or name is defined, an icon should be displayed.

**Comment by pekam** [comment]
> To add to the list: if no img, abrr, or name is defined, an icon should be displayed.

Created another ticket for this: #12
Feel free to provide more details there, eg. what icon to display.

**Comment by jouni** [comment]
Should the attribute/property name be `src` instead of `img`?

**Comment by pekam** [comment]
That was also discussed, but I don't remember exactly why we ended up with `img`.

@yuriy-fix I have a vague memory that maybe you had some argument for using `img`?

**Comment by Legioth** [comment]
The idea was that the `img` property refers to the implied `<img>` child element and `abbr` property refers to the implied `<abbr>` child element.
