### ISSUE TITLE
Avatar overlapping and masking

### ISSUE THREAD

**Issue by web-padawan** [vaadin/vaadin-avatar#26]
From @jouni in the Slack discussion:

The current implementation still ends up with fractional pixels, and that results in the avatars “jiggling” when you resize the browser. Also, the mask image clips tightly around the avatar, making it impossible to use an outer box shadow for the focus ring.

From @yuriy-fix at https://github.com/vaadin/vaadin-avatar/pull/24#discussion_r448281033:

Problems with calculating margins as it's calculated based on number of items and the `+N` avatar is not a part of those.

**Comment by jouni** [comment]
> Also, the mask image clips tightly around the avatar, making it impossible to use an outer box shadow for the focus ring.

Seems like this can’t be avoided when using a mask-image. Even though the mask extends outside the are of the element, the box shadow is still clipped.

**Comment by jouni** [comment]
Here’s the prototype I promised: https://jsbin.com/jifisol/1/edit

It has three custom properties that you can control:

- `--avatar-size`
- `--overlap`: controls how much the avatars are on top of each other in a group
- `--overlap-border`: controls the “safe area” between avatars, where the background color is shown through
- `--_focus-outline-width`: thought this could be extracted as a private property, to make just to make it easier to maintain if we ever decide to change the focus outline style in our theme.

I added a “reverse stacking” prototype while I was add it, to show that the same mask image can handle both cases, by adjusting the mask-position.

Also, note, that we don’t need to use base64 encoding for the mask-image. I’m not sure it makes it any smaller, and only adds a bit of processing overhead when the browser has to decode it.

**Comment by jouni** [comment]
Now I realize, that since I’m using the border for the focus outline (instead of a box-shadow, which doesn’t work), we would need something else for the user color border (#22).
