### ISSUE TITLE
vaadin-avatar-group: display multiple avatars

### ISSUE THREAD

**Issue by pekam** [vaadin/vaadin-avatar#6]
Create the `<vaadin-avatar-group>` component, which should either just display its slotted child `<vaadin-avatar>` elements in a row or have an `items` API, where each item object in the list can have `img`, `abbr` and `name` (from `vaadin-avatar`).
After the latest discussion we kind of agreed on the latter one, because the avatar data is very dynamic, in contrast to eg. `<vaadin-tabs>` which has declarative API.

**Comment by jouni** [comment]
If the `items` API is used, will the `<vaadin-avatar>` elements be inside the shadow root of the group?
