### ISSUE TITLE
New unconfigured avatar group shows a single clipped avatar

### ISSUE THREAD

**Issue by Legioth** [vaadin/vaadin-avatar#66]
```
someElement.appendChild(document.createElement("vaadin-avatar-group"));
```

is rendered like this

![Screen Shot 2020-08-20 at 10 49 44](https://user-images.githubusercontent.com/1294657/90732091-3eee4180-e2d3-11ea-9ea9-be35a442d010.png)

Also, the `aria-label` attribute value is quite confusing: `Currently undefined active users`. 

Explicitly assigning `[]` to `items` gives the expected empty rendering.

**Comment by web-padawan** [comment]
Confirmed the first issue (cropped avatar) with `1.0.0-alpha6` but not `1.0.0-alpha7`. It was apparently fixed by #57 

Regarding the second part (`aria-label`) - that's still an issue, will submit a PR to fix it.
