### ISSUE TITLE
Overflow item should never show +1

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-avatar#67]
Showing +1 has no benefit. Only show the overflow item for 2 or more items.

As an example,  if we have max=4, then when a fifth users joins, the group will show three avatars and then the overflow item. Said another way, the overflow item should be counted in the maximum amount of avatar items shown in the group.

**Comment by web-padawan** [comment]
Will be fixed by #65

**Comment by web-padawan** [comment]
> the overflow item should be counted in the maximum amount of avatar items shown in the group.

This might need to be fixed separately, and will be reflected in the documentation for `max` property.
