### ISSUE TITLE
Rename max property to max-items-visible

### ISSUE THREAD

**Issue by web-padawan** [vaadin/vaadin-avatar#70]
Currently, if both `width` CSS property and `max` property are set, the `max` property wins.

Discussed this and decided that `max` property can be removed (as we have auto overflow). Instead, we should:

- add a demo how showcasing auto overflow, using `notifyResize()` when e.g. parent component size is changed.
- use mutation observer to check `style` attribute changes and call `notifyResize()`

**Comment by pekam** [comment]
The max API should be removed in three places:
- [ ] web component
- [ ] `AvatarGroup.java` in `vaadin-avatar-flow`
- [ ] `CollaborationAvatarGroup.java` in `collaboration-engine`

**Comment by web-padawan** [comment]
Note, we previously discussed that `notifyResize()` should be called from `AvatarGroup` but if we use mutation observer, then this is maybe not necessary as the component itself would check for `style` attribute changes.

**Comment by web-padawan** [comment]
Update: discussed and concluded that removal would not help developer experience but current name should be changed. 

So the decision is to rename `max` to `max-items-visible` (should be done according to the list above).

**Comment by web-padawan** [comment]
Fixed by #74
