### ISSUE TITLE
The plus sign in "+5" when avatars are overflowing is not completely with a number larger than 9

### ISSUE THREAD

**Issue by eriklumme** [vaadin/vaadin-avatar#87]
Consider the following code

```
<vaadin-avatar-group id="avatarGroup" items={{items}} max-items-visible="3">
</vaadin-avatar-group>
```

Where `items` contains more than 13 items. At this point the overflow number is partly obscured.

![image](https://user-images.githubusercontent.com/29859656/96098319-a8a55900-0eda-11eb-87a1-23b3d0ae8b8b.png)

I think this boils down to whether 10+ avatars in one group is realistic. Maybe the overflow circle could be shown on top (on the z axis)?

**Comment by jouni** [comment]
Not a proper solution, but reversed stacking order (#89) would offer a suitable workaround at least.

**Comment by yuriy-fix** [comment]
Closed in favor of https://github.com/vaadin/vaadin-avatar/issues/89
