### ISSUE TITLE
RTL does not work in vaadin-avatar-group

### ISSUE THREAD

**Issue by Peppe** [vaadin/vaadin-avatar#90]
https://cdn.vaadin.com/vaadin-avatar/1.0.0/demo/

**Describe the bug**
Avatar group looks wrong when you turn on right-to-left direction

**To Reproduce**
1. Go to https://cdn.vaadin.com/vaadin-avatar/1.0.0/demo/
2. Open inspector
3. Choose the `<html>` -tag
4. Add `direction: rtl;` to the css for the tag

Notice that the order of the avatars is inverted, which is good, but then the cutout and spacing of the first and last avatar are wrong.

**Expected behavior**
The avatar group follows right-to-left practices and looks good.

**Screenshots**

Right to left (wrong):
![Screenshot 2020-10-22 at 10 04 39](https://user-images.githubusercontent.com/525503/96837206-b749be00-144e-11eb-8a67-1b8d2b066a81.png)

Left to right (correct):
![Screenshot 2020-10-22 at 10 04 49](https://user-images.githubusercontent.com/525503/96837164-a600b180-144e-11eb-8ac9-8be70cdf13aa.png)

**Versions**
`<vaadin-avatar>` 1.0.0
`Browser version: Chrome 86

**Comment by yuriy-fix** [comment]
Currently the `RTL` behavior which is controlled by `vaadin-dir-mixin` uses `rtl` attribute to apply the proper logic and styles. So if you apply `dir="rtl"` on the `html` tag it will work properly.

**Comment by Peppe** [comment]
You are very correct. Sorry for the misreport. I tested it and it works properly. Closing issue.
